modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/CreativeMD/CreativeCore/issues"
logoFile="creativecore.png"

[[mods]]
	modId="creativecore"
	version="2.0.0"
	displayName="CreativeCore"
	side="CLIENT"
	displayURL="https://minecraft.curseforge.com/projects/creativecore"
	authors="CreativeMD"
	description='''A simple but powerful coremod.'''